# Generated by Django 4.2.14 on 2024-07-13 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailModel',
            new_name='AccaountUsersAdmin',
       ),
    ]
