# Generated by Django 4.2.14 on 2024-07-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersregistrmodel',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='Прошел активацию'),
        ),
        migrations.AddField(
            model_name='usersregistrmodel',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Слать оповещение'),
        ),
        migrations.AddIndex(
            model_name='usersregistrmodel',
            index=models.Index(fields=['is_activated'], name='activated_indx'),
        ),
    ]
