# Generated by Django 4.2.14 on 2024-07-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_emailmodel_accaountusersadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccaountUsersAdmin',
            new_name='AccountUsersModel',
       ),
    ]
