# Generated by Django 4.2.14 on 2024-07-14 04:29

import account.models
import account.validators
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_accaountusersadmin_accountusersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRegistrModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(limit_value=30, message='Проверьте количество символов. Длина логина не больше 30 символов.'), django.core.validators.MinLengthValidator(limit_value=3, message='Проверьте количество символов. Минимальная длина          логина от 3 символов.'), account.validators.no_special_chars_validators, account.validators.min_length_validators])),
                ('password', models.CharField(help_text='Min - 10 символов. Max - 30 символов', max_length=30, validators=[django.core.validators.MaxLengthValidator(limit_value=30, message='Проверьте количество символов. Длина логина          не больше 30 символов.'), django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), 'Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.', 'invalid'), account.models.update_min_length_validators])),
                ('repassword', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(limit_value=30, message='Проверьте количество символов или равен содержимому строке выше.'), django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), 'Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.', 'invalid'), account.models.update_min_length_validators])),
                ('email', models.EmailField(help_text='that_your@email.adress', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Проверьте email-адрес.')])),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='AccountUsersModel',
        ),
    ]
