# Generated by Django 4.2.14 on 2024-07-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_usersregistrmodel_delete_accountusersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersregistrmodel',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
       ),
    ]
