# Generated by Django 4.2.14 on 2024-07-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_usersregistrmodel_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersregistrmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
