# Generated by Django 4.2.14 on 2024-07-20 09:48

import account.models
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0005_alter_usersregistrmodel_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
       ),
        migrations.AlterModelOptions(
            name='usersregistrmodel',
            options={'verbose_name_plural': 'new_users'},
       ),
        migrations.AlterModelManagers(
            name='usersregistrmodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
       ),
        migrations.RemoveField(
            model_name='usersregistrmodel',
            name='email',
       ),
        migrations.RemoveField(
            model_name='usersregistrmodel',
            name='id',
       ),
        migrations.RemoveField(
            model_name='usersregistrmodel',
            name='password',
       ),
        migrations.RemoveField(
            model_name='usersregistrmodel',
            name='repassword',
       ),
        migrations.RemoveField(
            model_name='usersregistrmodel',
            name='username',
       ),
        migrations.AddField(
            model_name='usersregistrmodel',
            name='password1',
            field=models.CharField(default='NULL', help_text='Min - 10 символов. Max - 30 символов', max_length=30, validators=[django.core.validators.MaxLengthValidator(limit_value=30, message='Проверьте количество символов. Длина логина          не больше 30 символов.'), django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), 'Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.', 'invalid'), account.models.update_min_length_validators]),
       ),
        migrations.AddField(
            model_name='usersregistrmodel',
            name='password2',
            field=models.CharField(default='NULL', max_length=30, validators=[django.core.validators.MaxLengthValidator(limit_value=30, message='Проверьте количество символов или равен содержимому строке выше.'), django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), 'Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.', 'invalid'), account.models.update_min_length_validators]),
       ),
        migrations.AddField(
            model_name='usersregistrmodel',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
       ),
    ]
