# Generated by Django 4.2.14 on 2024-07-21 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_accountuser_alter_usersregistrmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersregistrmodel',
            name='datetime',
       ),
    ]
