# Generated by Django 4.2.14 on 2024-07-21 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_usersregistrmodel_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersregistrmodel',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='usersregistrmodel',
            name='password2',
        ),
    ]
