# Generated by Django 4.2.14 on 2024-07-21 10:01

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0009_alter_usersregistrmodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersRegistrModel',
       ),
        migrations.CreateModel(
            name='UsersRegistrModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
       ),
    ]
