# Generated by Django 4.2.14 on 2024-07-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_delete_usersregistrmodel_usersregistrmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersregistrmodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
       ),
    ]
