# Generated by Django 4.2.14 on 2024-07-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_delete_accountuser_delete_usersregistrmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersregistrmodel',
            options={},
        ),
    ]
